<footer class="content-footer footer bg-footer-theme">
  <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
    <div class="mb-2 mb-md-0">
    <?php echo Settings::$getSiteName ? Settings::$getSiteName : ''?> © <script>
      document.write(new Date().getFullYear())
      </script>
      , all rights reserved  <a href="https://ya.ru" target="_blank" class="footer-link fw-bolder"> </a> <a href="https://ya.ru" target="_blank" class="footer-link fw-bolder"></a>
    </div>
    <div>
      
      Developed by <a href="https://t.me/notasuperman1" class="footer-link me-4 fw-bolder" target="_blank">Bormotov Alexandr</a>
      
    </div>
  </div>
</footer>