<?php  
if(isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin'):
  include $_SERVER['DOCUMENT_ROOT'].'/views/404.php';
  return;
endif;
include $_SERVER['DOCUMENT_ROOT'].'/views/components/header.phtml'; ?>

<!-- Content wrapper -->
<div class="content-wrapper">
  <!-- Content -->
  <div class="container-xxl flex-grow-1 container-p-y">
    
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Локатор /</span> Карта</h4>

    <!-- Встраиваемая карта -->
    <div class="card">
      <div class="card-body">
        <iframe src="https://hosting.wialon.com/locator/index.html?t=569a0920f1e58ba3eca2af8dfdd960102DFE6E5408AA4931F47B3616656DE99EBF31A5D3&directs=1&labels=1&tails=0" width="100%" height="600" style="border:0;"></iframe>
      </div>
    </div>

  </div>
  <!-- / Content -->

  <?php include $_SERVER['DOCUMENT_ROOT'].'/views/components/footer.phtml'; ?>
</div>
<!-- / Content wrapper -->
