<?php
   if (isset($_SESSION['userRole']) && $_SESSION['userRole'] !== 'superAdmin' && $_SESSION['userRole'] !== 'admin') :
       include $_SERVER['DOCUMENT_ROOT'] . '/views/404.php';
       return;
   endif;
   include $_SERVER['DOCUMENT_ROOT'] . '/views/components/header.phtml'; ?>
<div class="content-wrapper">
   <div class="container-xxl flex-grow-1 container-p-y">
      <h4 class="fw-bold py-3 mb-4">
         <span class="text-muted fw-light">Банкинг/</span> Банковские операции
      </h4>
      <div class="card">
         <div class="flexDiv">
            <h5 class="card-header">Банковские операции</h5>
            <div>
               <select id="smallSelect" class="form-select form-select-sm">
                  <option value="all" <?php echo isset($_GET['filter']) && $_GET['filter'] === 'all' ? 'selected' : 'selected'; ?> >Все</option>
                  <option value="deposits" <?php echo isset($_GET['filter']) && $_GET['filter'] === 'deposits' ? 'selected' : ''; ?>>Пополнения</option>
                  <option value="withdraws" <?php echo isset($_GET['filter']) && $_GET['filter'] === 'withdraws' ? 'selected' : ''; ?>>Выплаты</option>
               </select>
            </div>
         </div>
         <span class="ms-3" id="deleteErr"></span>
         <div class="table-responsive text-nowrap">
            <table class="table">
               <thead>
                  <tr>
                     <th>Дата</th>
                     <th>Сумма</th>
                     <th>Тип транзакции</th>
                     <th>Кем отправлена</th>
                     <th>Цель</th>
                     <th>Действия</th>
                  </tr>
               </thead>
               <tbody class="table-border-bottom-0"></tbody>
            </table>
         </div>
         <div class="card-body">
            <div class="row">
               <div class="col">
                  <div class="demo-inline-spacing">
                     <nav aria-label="Page navigation">
                        <ul class="pagination"></ul>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <hr class="my-5">
      <div class="modal fade" id="modalScrollable" tabindex="-1" aria-hidden="true">
         <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
               <div class="modal-header">
                  <h5 class="modal-title" id="modalScrollableTitle">Подробнее о транзакции</h5>
               </div>
               <div class="modal-body" id="detailsBody">
                  <div class="text-center fs-3">
                     <i class="bx bx-loader-alt bx-spin fs-1"></i>
                  </div>
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-outline-secondary" id="closeDetails" data-bs-dismiss="modal">Закрыть</button>
               </div>
            </div>
         </div>
      </div>
   </div>
   <?php include $_SERVER['DOCUMENT_ROOT'] . '/views/components/footer.phtml'; ?>
   <script src="/views/api/bank.API.js"></script>
   <div class="content-backdrop fade"></div>
</div>
<script src="/views/assets/vendor/libs/jquery/jquery.js"></script>
<script src="/views/assets/vendor/libs/popper/popper.js"></script>
<script src="/views/assets/vendor/js/bootstrap.js"></script>
<script src="/views/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="/views/assets/vendor/js/menu.js"></script>
<script src="/views/assets/js/pages